apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    url: timescaledb:5432
    database: mogao_monitor
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
    editable: false

  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    editable: false
